networks:
  frontend:
    external: true
    name: docker_frontend
  backend:
    external: true
    name: docker_backend

services:
  legal-document-chunking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legal-document-chunking
    restart: always
    networks:
      - frontend
      - backend
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      # Service configuration
      - "traefik.http.services.chunking.loadbalancer.server.port=8000"
      - "traefik.http.services.chunking.loadbalancer.server.scheme=http"
      - "traefik.http.services.chunking.loadbalancer.passhostheader=true"
      # Router configuration
      - "traefik.http.routers.chunking.entrypoints=https"
      - "traefik.http.routers.chunking.rule=Host(`chunk.chantierdoc.com`)"
      - "traefik.http.routers.chunking.tls=true"
      - "traefik.http.routers.chunking.tls.certresolver=cloudflare"
      - "traefik.http.routers.chunking.service=chunking"
      - "traefik.http.routers.chunking.middlewares=rate-limit@file"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M